name = "prairie-cnk"
compatibility_date = "2025-01-25"
pages_build_output_dir = "out"

[placement]
mode = "smart"
hint = "wnam"

[[d1_databases]]
binding = "DB"
database_name = "prairie-cnk-db"
database_id = "dc61e8a3-e575-4abb-93d5-e0eca85ae039"
